services:
  - type: static_site
    name: sankeymatic-rebuild
    buildCommand: npm install && npx vite build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
